services:
  - type: web
    name: gmd-tool
    env: python
    startCommand: gunicorn --timeout 120 --workers 3 --worker-class gevent --worker-connections 200 --max-requests 1000 --keepalive 75 app:app
